language: node_js
sudo: true
env:
  matrix:
    - MONGODB=4.2.5
  global:
    - DB_HOST=0.0.0.0
    - DB_PORT=27017
    - DB_USERNAME=
    - DB_PASSWORD=
    - DB_DATABASE=senren_test

    - API_HOST=0.0.0.0
    - API_PORT=5000
    - API_BEARER_SECRET_TOKEN=supersecret
    - API_JWT_SECRET_TOKEN=supersecret
    - API_SESSION_SECRET_TOKEN=supersecretmusthave32orgreaterlength
    - API_SESSION_COOKIE_SECURE=false

matrix:
  fast_finish: true

node_js:
  - 12

install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --version
  - npm install

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/mongodb.log --fork

script:
  - npm run lint
  - npm test

after_script:
  - pkill mongod
