language: node_js
sudo: true
env:
  global:
    - DB_HOST=0.0.0.0
    - DB_PORT=27017
    - DB_USERNAME=
    - DB_PASSWORD=
    - DB_DATABASE=senren_test

    - API_HOST=0.0.0.0
    - API_PORT=5000
    - API_BEARER_SECRET_TOKEN=supersecret
    - API_JWT_SECRET_TOKEN=supersecret
    - API_SESSION_SECRET_TOKEN=supersecretmusthave32orgreaterlength
    - API_SESSION_COOKIE_SECURE=false
node_js:
  - 12
install:
  - npm install
script:
  - npm run lint
  - npm test
services: mongodb
