services:
  api:
    build: ./
    ports: 
      - "8080:8080"
    volumes:
      - ./api:/usr/src/app
    links:
      - db
    command: bash -c "bash ./wait-for-it.sh db:27017 -q -- cargo watch -x run"

  db:
    image: mongo:3.2.20
    ports:
      - 27017
